services:
  fastapi:
    build:
      context: ..
      dockerfile: docker/fastapi/Dockerfile
    ports:
      - ${FASTAPI_PORT}:8000
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASS}
      - DB_NAME=${POSTGRES_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - TOKEN_WHITE_LIST_TABLE=${TOKEN_WHITE_LIST_TABLE}
    volumes:
      - ../src:/src
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgresql
    restart: always

  alembic:
    build:
      context: ..
      dockerfile: docker/alembic/Dockerfile
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASS}
      - DB_NAME=${POSTGRES_NAME}
    volumes:
      - ../src:/src

  postgresql:
    image: postgres:17.6
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always

  # nginx:
  #   image: nginx:1.29.2
  #   ports:
  #     - ${NGINX_PORT}:80
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - fastapi
  #   restart: always
